export interface BuiltinScheme {
  id: string;
  name: string;
  category: string;
  ministry: string | null;
  description: string | null;
  benefits: string | null;
  eligibility_text: string | null;
  rules: Record<string, any>;
  official_url: string | null;
  source: string | null;
  state_specific: boolean;
  is_active: boolean;
  status_text: string;
  application_deadline: string;
  scraped_at: string;
  created_at: string;
}

export const BUILTIN_SCHEMES: BuiltinScheme[] = [
  // ── Farmer ──────────────────────────────────────────────────────────────
  {
    id: "pm-kisan",
    name: "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    description: "Direct income support of ₹6,000/year to small and marginal farmers in three equal instalments of ₹2,000 each.",
    benefits: "₹6,000 per year (₹2,000 every 4 months) direct bank transfer",
    eligibility_text: "Small and marginal farmers with landholding up to 2 hectares. Family income from farming activities only.",
    rules: { max_land_ha: 2, requires_aadhaar: true, bank_account: true },
    official_url: "https://pmkisan.gov.in/",
    source: "pmindia.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-fasal-bima",
    name: "PM Fasal Bima Yojana (PMFBY)",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    description: "Comprehensive crop insurance providing financial support to farmers suffering crop loss/damage due to unforeseen calamities, pests & diseases.",
    benefits: "Insurance coverage for crop loss; premium subsidised by government (1.5–5% for farmers)",
    eligibility_text: "All farmers including sharecroppers and tenant farmers growing notified crops.",
    rules: { premium_max_pct: 5, covers_natural_calamities: true },
    official_url: "https://pmfby.gov.in/",
    source: "pmindia.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-kisan-maan-dhan",
    name: "PM Kisan Maan-Dhan Yojana",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    description: "Voluntary and contributory pension scheme for small and marginal farmers to provide them social security.",
    benefits: "₹3,000/month pension after age 60",
    eligibility_text: "Small and marginal farmers aged 18–40 years with cultivable land up to 2 hectares.",
    rules: { min_age: 18, max_age: 40, max_land_ha: 2, entry_age_range: "18-40" },
    official_url: "https://maandhan.in/",
    source: "pmindia.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-kusum",
    name: "PM-KUSUM (Kisan Urja Suraksha Uttham Mahabhiyan)",
    category: "farmer",
    ministry: "Ministry of New and Renewable Energy",
    description: "Scheme for installation of solar pumps and grid-connected solar power plants for farmers.",
    benefits: "Solar powered agricultural pumps; financial assistance up to 60% of cost",
    eligibility_text: "Farmers with barren/uncultivable land or requiring irrigation. State-specific implementation.",
    rules: { solar_pump: true, subsidy_pct: 60 },
    official_url: "https://mnre.gov.in/solar/schemes",
    source: "mnre.gov.in",
    state_specific: true,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "kcc-scheme",
    name: "Kisan Credit Card (KCC) Scheme",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    description: "Provides farmers with timely credit support from the banking system for agricultural operations and maintenance.",
    benefits: "Short-term credit up to ₹3 lakh at 4% interest rate with crop insurance",
    eligibility_text: "All farmers, SHGs, and Joint Liability Groups of farmers including tenant farmers.",
    rules: { max_credit_lakh: 3, interest_rate_pct: 4 },
    official_url: "https://www.nabard.org/",
    source: "nabard.org",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── Student ─────────────────────────────────────────────────────────────
  {
    id: "nsp-central-scholarships",
    name: "National Scholarship Portal (NSP) Scholarships",
    category: "student",
    ministry: "Ministry of Education",
    description: "Central umbrella portal providing multiple scholarship schemes for pre-matric, post-matric and merit-based scholarships.",
    benefits: "Scholarships from ₹500 to ₹20,000+ per year depending on scheme and level of education",
    eligibility_text: "Students from Class 1 to PhD depending on particular scheme. Income limit ₹2.5–8 lakh per annum.",
    rules: { max_income: 800000, covers: ["pre-matric", "post-matric", "merit-based"] },
    official_url: "https://scholarships.gov.in/",
    source: "scholarships.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-vidya-lakshmi",
    name: "PM Vidya Lakshmi Education Loan",
    category: "student",
    ministry: "Ministry of Education",
    description: "Single window for students to access education loans and scholarships from multiple banks.",
    benefits: "Education loans at subsidised interest rates; full interest subsidy during moratorium for EWS/LIG",
    eligibility_text: "Students seeking admission to recognised colleges in India or abroad.",
    rules: { interest_subsidy: true, ews_lig_eligible: true },
    official_url: "https://www.vidyalakshmi.co.in/",
    source: "vidyalakshmi.co.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-e-vidya",
    name: "PM eVidya Digital Learning",
    category: "student",
    ministry: "Ministry of Education",
    description: "Multi-mode access to digital/online education to ensure uninterrupted learning.",
    benefits: "Free access to educational content via DIKSHA portal, DTH channels, radio, and podcasts",
    eligibility_text: "All students from Class 1 to 12 across India.",
    rules: { free_access: true, digital_platform: true },
    official_url: "https://diksha.gov.in/",
    source: "education.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "cbse-merit-scholarship",
    name: "CBSE Merit Scholarship Scheme",
    category: "student",
    ministry: "Ministry of Education",
    description: "Scholarship for single girl child studying in CBSE affiliated schools.",
    benefits: "₹500/month scholarship for 2 years in Class 11–12",
    eligibility_text: "Single girl child who scored at least 60% in Class X CBSE board examination.",
    rules: { min_marks_pct: 60, single_girl_child: true },
    official_url: "https://cbse.gov.in/",
    source: "cbse.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── Health ───────────────────────────────────────────────────────────────
  {
    id: "ayushman-bharat-pmjay",
    name: "Ayushman Bharat — PM Jan Arogya Yojana (AB-PMJAY)",
    category: "health",
    ministry: "Ministry of Health & Family Welfare",
    description: "World's largest government-funded health assurance scheme providing health cover of ₹5 lakh per family per year.",
    benefits: "₹5 lakh/year health cover for hospitalisation; cashless treatment at 24,000+ empanelled hospitals",
    eligibility_text: "Families in bottom 40% socio-economic group identified through SECC database. No family size limit.",
    rules: { health_cover_lakh: 5, cashless: true, secc_database: true },
    official_url: "https://pmjay.gov.in/",
    source: "pmjay.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-surakshit-matritva-abhiyan",
    name: "Pradhan Mantri Surakshit Matritva Abhiyan",
    category: "health",
    ministry: "Ministry of Health & Family Welfare",
    description: "Provides assured, comprehensive and quality antenatal care, free of cost, on the 9th day of every month.",
    benefits: "Free ante-natal checkups on every 9th of the month at health facilities",
    eligibility_text: "All pregnant women in their 2nd or 3rd trimester.",
    rules: { free_antenatal_care: true, monthly_9th_checkup: true },
    official_url: "https://pmsma.nhp.gov.in/",
    source: "nhp.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── Women ────────────────────────────────────────────────────────────────
  {
    id: "pm-matru-vandana",
    name: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    category: "women",
    ministry: "Ministry of Women and Child Development",
    description: "Maternity benefit programme providing cash incentives to pregnant and lactating mothers for first living child.",
    benefits: "₹5,000 in three instalments during pregnancy and after childbirth",
    eligibility_text: "All pregnant and lactating women except those in regular government employment.",
    rules: { instalments: 3, total_benefit: 5000, first_child: true },
    official_url: "https://wcd.nic.in/",
    source: "wcd.nic.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "sukanya-samriddhi-yojana",
    name: "Sukanya Samriddhi Yojana (SSY)",
    category: "women",
    ministry: "Ministry of Finance",
    description: "Small deposit scheme for the girl child to build a fund for higher education and marriage.",
    benefits: "8.2% per annum interest (tax-free); ₹250 min to ₹1.5 lakh max annual deposit",
    eligibility_text: "Girl child up to 10 years of age. Account opened by parent/guardian.",
    rules: { max_age_girl: 10, min_deposit: 250, max_deposit_pa: 150000, interest_rate_pct: 8.2 },
    official_url: "https://www.indiapost.gov.in/",
    source: "indiapost.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "beti-bachao-beti-padhao",
    name: "Beti Bachao Beti Padhao",
    category: "women",
    ministry: "Ministry of Women and Child Development",
    description: "Addresses declining Child Sex Ratio and promotes welfare and education of the girl child.",
    benefits: "Awareness campaigns; school enrolment of girls; community mobilisation for girl child welfare",
    eligibility_text: "All girl children, particularly in districts with low Child Sex Ratio.",
    rules: { focus_on_girl_child: true, awareness_campaign: true },
    official_url: "https://wcd.nic.in/bbbp-schemes",
    source: "wcd.nic.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-ujjwala-yojana",
    name: "Pradhan Mantri Ujjwala Yojana (PMUY)",
    category: "women",
    ministry: "Ministry of Petroleum & Natural Gas",
    description: "Free LPG connections to women from BPL households to replace unclean cooking fuels.",
    benefits: "Free LPG connection (cylinder + regulator); ₹1,600 cash assistance; first refill free",
    eligibility_text: "Women over 18 from BPL household. PMUY 2.0 extended to migrants and rent-dwellers.",
    rules: { min_age: 18, bpl: true, free_connection: true },
    official_url: "https://www.pmujjwalayojana.com/",
    source: "petroleum.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── Housing & General ──────────────────────────────────────────────────
  {
    id: "pm-awas-yojana-urban",
    name: "Pradhan Mantri Awas Yojana — Urban (PMAY-U)",
    category: "general",
    ministry: "Ministry of Housing and Urban Affairs",
    description: "Housing for All mission to provide pucca housing to urban poor.",
    benefits: "Subsidy up to ₹2.67 lakh on home loan; in-situ slum rehabilitation; affordable housing",
    eligibility_text: "EWS/LIG/MIG families without pucca house in any part of India.",
    rules: { beneficiary_categories: ["EWS", "LIG", "MIG"], subsidy_max_lakh: 2.67 },
    official_url: "https://pmaymis.gov.in/",
    source: "mohua.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-awas-yojana-grameen",
    name: "Pradhan Mantri Awas Yojana — Gramin (PMAY-G)",
    category: "general",
    ministry: "Ministry of Rural Development",
    description: "Financial assistance to rural households to construct pucca houses with basic amenities.",
    benefits: "₹1.2 lakh (plains) or ₹1.3 lakh (hills/difficult areas) for house construction",
    eligibility_text: "Homeless rural households or those living in zero room, kutcha or dilapidated houses.",
    rules: { plains_benefit: 120000, hills_benefit: 130000, secc_based: true },
    official_url: "https://pmayg.nic.in/",
    source: "rural.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── Employment & Business ──────────────────────────────────────────────
  {
    id: "mgnregs",
    name: "MGNREGS (Mahatma Gandhi National Rural Employment Guarantee Scheme)",
    category: "general",
    ministry: "Ministry of Rural Development",
    description: "Legal guarantee of at least 100 days of unskilled wage employment per year to rural households.",
    benefits: "100 days/year guaranteed employment; wages ₹220–350/day depending on state",
    eligibility_text: "Any adult member of a rural household willing to do unskilled manual work.",
    rules: { min_days_guaranteed: 100, rural_only: true, unskilled_only: true },
    official_url: "https://nrega.nic.in/",
    source: "rural.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-mudra-yojana",
    name: "Pradhan Mantri MUDRA Yojana (PMMY)",
    category: "general",
    ministry: "Ministry of Finance",
    description: "Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises.",
    benefits: "Shishu (up to ₹50K), Kishore (₹50K–5L), Tarun (₹5L–10L) — collateral-free loans",
    eligibility_text: "Non-farm micro/small enterprises including individuals, proprietorships, partnerships.",
    rules: { max_loan_lakh: 10, no_collateral: true },
    official_url: "https://www.mudra.org.in/",
    source: "mudra.org.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "pm-jan-dhan-yojana",
    name: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
    category: "general",
    ministry: "Ministry of Finance",
    description: "National mission for financial inclusion to ensure access to financial services for all households.",
    benefits: "Zero-balance bank account; RuPay debit card; ₹2 lakh accident insurance; ₹10,000 overdraft",
    eligibility_text: "Any Indian citizen without a bank account. No minimum balance required.",
    rules: { zero_balance: true, accident_insurance: 200000, overdraft: 10000 },
    official_url: "https://pmjdy.gov.in/",
    source: "pmjdy.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── SC/ST & Social Welfare ─────────────────────────────────────────────
  {
    id: "post-matric-scholarship-sc",
    name: "Post Matric Scholarships for SC Students",
    category: "sc_st",
    ministry: "Ministry of Social Justice & Empowerment",
    description: "Financial assistance to SC students to enable them to complete post-matriculation education.",
    benefits: "Maintenance allowance + tuition fees (varies by course); ₹550–1,200/month",
    eligibility_text: "SC students studying in Class 11 and above. Annual family income up to ₹2.5 lakh.",
    rules: { max_income: 250000, sc_only: true, post_matric: true },
    official_url: "https://scholarships.gov.in/",
    source: "socialjustice.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "post-matric-scholarship-st",
    name: "Post Matric Scholarships for ST Students",
    category: "sc_st",
    ministry: "Ministry of Tribal Affairs",
    description: "Financial assistance to Scheduled Tribe students to pursue post-matric studies.",
    benefits: "Full tuition fee reimbursement + maintenance allowance; hostel charges covered",
    eligibility_text: "ST students from Class 11 onwards. Annual family income up to ₹2.5 lakh.",
    rules: { max_income: 250000, st_only: true, post_matric: true },
    official_url: "https://tribal.nic.in/",
    source: "tribal.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── BPL & Ration ──────────────────────────────────────────────────────
  {
    id: "pm-garib-kalyan-anna-yojana",
    name: "PM Garib Kalyan Anna Yojana (PMGKAY)",
    category: "bpl",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    description: "Free food grain scheme providing 5 kg of rice/wheat per person per month to NFSA beneficiaries.",
    benefits: "5 kg free food grain per person per month (rice/wheat)",
    eligibility_text: "All NFSA beneficiaries — Antyodaya and Priority Household ration card holders.",
    rules: { kg_per_person_per_month: 5, free: true, nfsa_card_required: true },
    official_url: "https://nfsa.gov.in/",
    source: "nfsa.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "one-nation-one-ration-card",
    name: "One Nation One Ration Card (ONORC)",
    category: "bpl",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    description: "Allows NFSA beneficiaries to claim entitled food grains from any Fair Price Shop in India.",
    benefits: "Portability of ration card; claim subsidised food from any FPS across India",
    eligibility_text: "All NFSA ration card holders including migrant workers.",
    rules: { pan_india_portability: true, ration_card_required: true },
    official_url: "https://impds.nic.in/",
    source: "nfsa.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },

  // ── Senior Citizen & Disabled ──────────────────────────────────────────
  {
    id: "indira-gandhi-national-old-age-pension",
    name: "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
    category: "senior_citizen",
    ministry: "Ministry of Rural Development",
    description: "Pension scheme for BPL elderly persons to provide social security.",
    benefits: "₹200–500/month (Centre); states add additional contribution",
    eligibility_text: "Persons aged 60 years and above belonging to BPL household.",
    rules: { min_age: 60, bpl: true, monthly_pension_centre: 500 },
    official_url: "https://nsap.nic.in/",
    source: "rural.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "disabled-scholarship-nsdcs",
    name: "National Scholarship for Disabled Students",
    category: "disabled",
    ministry: "Ministry of Social Justice & Empowerment",
    description: "Scholarship to students with disability for pursuing professional and technical courses.",
    benefits: "₹3,000–10,000 per annum for day scholars; ₹5,000–15,000 for hostellers",
    eligibility_text: "Students with minimum 40% disability studying at Class 9 and above. Family income up to ₹2.5 lakh.",
    rules: { min_disability_pct: 40, max_income: 250000 },
    official_url: "https://scholarships.gov.in/",
    source: "socialjustice.gov.in",
    state_specific: false,
    is_active: true,
    status_text: "Active",
    application_deadline: "Ongoing / Open",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];
