-- ─────────────────────────────────────────────────────────────────────────────
-- CIVIS AI — Seed Government Schemes
-- Run AFTER schema.sql in your Supabase SQL editor
-- ─────────────────────────────────────────────────────────────────────────────

insert into schemes (id, name, category, description, benefits, eligibility_text, rules, ministry, official_url)
values

('pm_kisan',
 'PM-KISAN',
 'farmer',
 'Direct income support of ₹6,000/year to small and marginal farmer families.',
 '₹6,000/year in 3 equal installments of ₹2,000',
 'Land-owning farmer families with cultivable land up to 2 hectares.',
 '{"categories": ["farmer"], "income_max": 200000, "age_min": 18, "age_max": 70}',
 'Ministry of Agriculture & Farmers Welfare',
 'https://pmkisan.gov.in'),

('ayushman_bharat',
 'Ayushman Bharat (PM-JAY)',
 'health',
 'Health insurance cover of ₹5 lakh per family per year for hospitalization.',
 '₹5 lakh/year health insurance cover for secondary & tertiary care',
 'BPL and low-income families as per SECC 2011 data.',
 '{"categories": ["bpl","general","sc_st","obc","farmer","disabled","women"], "income_max": 300000, "age_min": 0, "age_max": 120}',
 'Ministry of Health and Family Welfare',
 'https://pmjay.gov.in'),

('pm_ujjwala',
 'PM Ujjwala Yojana',
 'women',
 'Free LPG connections to women from BPL households for clean cooking fuel.',
 'Free LPG connection + first refill cylinder + stove (hotplate)',
 'Women from BPL households without existing LPG connection.',
 '{"categories": ["women","bpl"], "income_max": 200000, "age_min": 18, "age_max": 60}',
 'Ministry of Petroleum and Natural Gas',
 'https://pmuy.gov.in'),

('post_matric_scholarship',
 'Post Matric Scholarship (SC/ST/OBC)',
 'student',
 'Financial assistance for SC/ST/OBC students in post-matriculation and post-secondary education.',
 'Full tuition fee reimbursement + monthly maintenance allowance (₹230–₹1,200)',
 'SC/ST/OBC students with family income below ₹2.5 lakh/year.',
 '{"categories": ["student","sc_st","obc"], "income_max": 250000, "age_min": 15, "age_max": 30}',
 'Ministry of Social Justice and Empowerment',
 'https://scholarships.gov.in'),

('youth_scholarship',
 'Youth Scholarship Scheme',
 'student',
 'Merit-cum-means scholarship for economically weaker students pursuing higher education.',
 '₹12,000/year scholarship stipend',
 'Young students with minimum 60% marks and annual family income below ₹5 lakh.',
 '{"categories": ["student","general","obc","sc_st","bpl"], "income_max": 500000, "age_min": 16, "age_max": 30}',
 'Ministry of Education',
 'https://scholarships.gov.in'),

('mnrega',
 'MNREGA',
 'general',
 'Guaranteed 100 days of wage employment per year to rural household adults who volunteer to do unskilled manual work.',
 '100 days guaranteed employment at minimum wage (₹200–₹350/day)',
 'Any adult member of a rural household willing to do unskilled manual work.',
 '{"categories": ["general","farmer","bpl","sc_st","obc","women","disabled"], "income_max": 300000, "age_min": 18, "age_max": 80}',
 'Ministry of Rural Development',
 'https://nrega.nic.in'),

('mudra_loan',
 'MUDRA Loan (PM Mudra Yojana)',
 'general',
 'Collateral-free micro-enterprise loans from ₹50,000 to ₹10 lakh for non-farm businesses. Three tiers: Shishu (≤₹50K), Kishore (₹50K–5L), Tarun (₹5L–10L).',
 'Loans up to ₹10 lakh at subsidized interest rates without collateral',
 'Any Indian citizen with a non-farm income-generating business plan/activity.',
 '{"categories": ["general","obc","sc_st","women","farmer"], "income_max": 1500000, "age_min": 18, "age_max": 65}',
 'Ministry of Finance',
 'https://mudra.org.in'),

('disability_pension',
 'Indira Gandhi National Disability Pension',
 'disabled',
 'Monthly pension support for persons with severe disabilities (80% or above) living below the poverty line.',
 '₹300–500/month pension + state top-up benefits',
 'BPL persons with 80%+ disability, aged 18–79 years.',
 '{"categories": ["disabled","bpl"], "income_max": 150000, "age_min": 18, "age_max": 79}',
 'Ministry of Rural Development',
 'https://nsap.nic.in'),

('senior_pension',
 'Indira Gandhi Old Age Pension',
 'senior_citizen',
 'Monthly pension for destitute elderly persons aged 60 years and above from BPL households.',
 '₹200/month (60–79 years) or ₹500/month (80+ years)',
 'BPL individuals aged 60 years and above.',
 '{"categories": ["senior_citizen","bpl","general"], "income_max": 150000, "age_min": 60, "age_max": 120}',
 'Ministry of Rural Development',
 'https://nsap.nic.in'),

('pm_awas_gramin',
 'PM Awas Yojana (Gramin)',
 'bpl',
 'Financial assistance for construction of pucca houses for rural BPL families who are homeless or living in kutcha houses.',
 '₹1.20–1.30 lakh (plains) / ₹1.30–1.50 lakh (hilly areas) for house construction',
 'Homeless or kutcha-house BPL families in rural areas (SECC 2011 priority list).',
 '{"categories": ["bpl","sc_st","general","farmer"], "income_max": 200000, "age_min": 18, "age_max": 80}',
 'Ministry of Rural Development',
 'https://pmayg.nic.in'),

('standup_india',
 'Stand-Up India',
 'women',
 'Bank loans between ₹10 lakh to ₹1 crore for setting up greenfield enterprises in manufacturing, services or trade sector by SC/ST and women entrepreneurs.',
 'Composite loan ₹10 lakh – ₹1 crore (75% of project cost) for greenfield enterprises',
 'SC/ST or Women entrepreneurs above 18 years with no existing loan default.',
 '{"categories": ["women","sc_st"], "income_max": 5000000, "age_min": 18, "age_max": 65}',
 'Ministry of Finance',
 'https://standupmitra.in'),

('nps',
 'National Pension Scheme (NPS)',
 'general',
 'Voluntary contributory pension system for organized and unorganized sector workers to build a retirement corpus with market-linked returns and tax benefits.',
 'Market-linked pension corpus + tax deduction under 80CCD(1B) up to ₹50,000 extra',
 'Indian citizen aged 18–70 years (both salaried and self-employed).',
 '{"categories": ["general","farmer","women","obc","sc_st"], "income_max": 10000000, "age_min": 18, "age_max": 70}',
 'Ministry of Finance / PFRDA',
 'https://npscra.nsdl.co.in')

on conflict (id) do update set
  name            = excluded.name,
  description     = excluded.description,
  benefits        = excluded.benefits,
  eligibility_text = excluded.eligibility_text,
  rules           = excluded.rules,
  ministry        = excluded.ministry,
  official_url    = excluded.official_url,
  is_active       = true;
